/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import conexion.ConnectionTableDB;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Advantech Digital
 */
public class DatosGasolinera extends javax.swing.JFrame {

    ConnectionTableDB conn;
    private File file;
    private FileInputStream stream;
    private String USER, PASSWORD, DB, consulta, eds, pto1, pto2, ptos;
    String[] pto;
    private boolean fileChanged = false;
    private int puntosEmision;

    /**
     * Creates new form DatosGasolinera
     */
    public DatosGasolinera(String usuario, String password) {
        USER = usuario;
        PASSWORD = password;
        DB = "adv_facturacion";
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader("eds.adv"));
            eds = br.readLine();
            consulta = "SELECT razon_social, ruc, direccion, email_estacion, despachadores_turno, tipo_ambiente, "
                    + "obligado_llevar_contabilidad, nombre_comercial, contribuyente_especial, tipo_cierre_turnos, "
                    + "AES_DECRYPT(contraseña_mail, 'thekey'), secuencia1_factura, certificado_digital "
                    + "FROM datos_gasolinera";
            conn = new ConnectionTableDB(USER, PASSWORD, DB, consulta, false);
            initComponents();
            setSize(900, 600);
            frameEmision.setSize(900, 600);
            frameEmision.setUndecorated(true);
            txtEDS.setText(eds.toUpperCase());
            if (conn.getRowCount() == 0) {
                btnGuardar.setText("Guardar");
            } else {
                btnGuardar.setText("Editar");
                txtRazonSocial.setText((String) conn.getValueAt(0, 0));
                txtRUC.setText((String) conn.getValueAt(0, 1));
                txtDireccion.setText((String) conn.getValueAt(0, 2));
                txtPropietario.setText((String) conn.getValueAt(0, 3));
                txtDespachadores.setText(String.valueOf(conn.getValueAt(0, 4)));
                cbxAmbiente.setSelectedIndex(Integer.parseInt((String) conn.getValueAt(0, 5)) - 1);
                chkContabilidad.setSelected(((String) conn.getValueAt(0, 6)).equalsIgnoreCase("SI"));
                txtNombreComercial.setText((String) conn.getValueAt(0, 7));
                txtContribuyente.setText((String) conn.getValueAt(0, 8));
                txtEstablecimiento.setText((String) conn.getValueAt(0, 11));
                if (conn.getValueAt(0, 12) != null)
                    txtCertificado.setText("Certificado en Uso");
                else
                    txtCertificado.setText("Sin Certificado");
                cbxTurno.setSelectedIndex((Integer) conn.getValueAt(0, 9) - 1);
                conn.consulta("SELECT s2 FROM punto_emision ORDER BY s2");
                for (int i = 0; i < conn.getRowCount(); i++) {
                    cbxEmision.addItem((String)conn.getValueAt(i, 0));
                }
                puntosEmision = cbxEmision.getItemCount();
                java.sql.ResultSet rs = conn.stSentencias.executeQuery("SELECT AES_DECRYPT(contraseña_mail, 'thekey'), "
                        + "AES_DECRYPT(contraseña_certificado, 'thekey') "
                        + "FROM datos_gasolinera");
                java.sql.Blob mail = null, certificado = null;
                if (rs.next()) {
                    mail = rs.getBlob(1);
                    certificado = rs.getBlob(2);
                }
                if (mail != null) {
                    passClaveEmail.setText(new String(mail.getBytes(1, (int) mail.length())));
                }
                if (certificado != null) {
                    passClave.setText(new String(certificado.getBytes(1, (int) certificado.length())));
                }
            }
        } catch (SQLException | IOException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameEmision = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPtoEmision = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAutorizacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelarPto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAPtos = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblEDS = new javax.swing.JLabel();
        txtEDS = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        lblRazonSocial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        lblRUC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        lblNombreComercial = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chkContabilidad = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContribuyente = new javax.swing.JTextField();
        lblContribuyente = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        lblPropietario = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        passClaveEmail = new javax.swing.JPasswordField();
        lblClaveEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEstablecimiento = new javax.swing.JTextField();
        lblEstablecimiento = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbxEmision = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtDespachadores = new javax.swing.JTextField();
        lblDespachadores = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbxAmbiente = new javax.swing.JComboBox();
        lblAmbiente = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCertificado = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        passClave = new javax.swing.JPasswordField();
        lblClave = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbxTurno = new javax.swing.JComboBox();
        lblTuno = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        frameEmision.setTitle("Puntos de Emisión");
        frameEmision.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Punto de Emisión:");

        txtPtoEmision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("N° Autorizacion:");

        txtAutorizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fecha Vencimiento:");

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnAdd)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPtoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAutorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        frameEmision.getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel5.add(btnAceptar);

        btnCancelarPto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarPto.setText("Cancelar");
        btnCancelarPto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPtoActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelarPto);

        frameEmision.getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        txtAPtos.setColumns(20);
        txtAPtos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtAPtos.setRows(5);
        jScrollPane1.setViewportView(txtAPtos);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(String.format("%15s   %-70s%15s",
            "Pto. Emisión", "Nro. Autorización", "Fecha Vencimiento"));
    jPanel6.add(jLabel12, java.awt.BorderLayout.PAGE_START);

    frameEmision.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

    frameEmision.getAccessibleContext().setAccessibleParent(this);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Datos de la Estación de Servicio");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosed(java.awt.event.WindowEvent evt) {
            formWindowClosed(evt);
        }
    });

    lblEDS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lblEDS.setText("Estacion de Servicio:");
    jPanel1.add(lblEDS);

    txtEDS.setEditable(false);
    txtEDS.setColumns(30);
    txtEDS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jPanel1.add(txtEDS);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    jPanel2.setLayout(new java.awt.GridLayout(0, 3, 10, 0));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Razón Social:");
    jPanel2.add(jLabel1);

    txtRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtRazonSocial.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtRazonSocialFocusLost(evt);
        }
    });
    txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtRazonSocialKeyTyped(evt);
        }
    });
    jPanel2.add(txtRazonSocial);

    lblRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblRazonSocial.setText("*");
    jPanel2.add(lblRazonSocial);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("RUC:");
    jPanel2.add(jLabel3);

    txtRUC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtRUC.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtRUCFocusLost(evt);
        }
    });
    txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtRUCKeyTyped(evt);
        }
    });
    jPanel2.add(txtRUC);

    lblRUC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblRUC.setText("*");
    jPanel2.add(lblRUC);

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel5.setText("Nombre Comercial:");
    jPanel2.add(jLabel5);

    txtNombreComercial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtNombreComercial.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtNombreComercialFocusLost(evt);
        }
    });
    jPanel2.add(txtNombreComercial);

    lblNombreComercial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblNombreComercial.setText("*");
    jPanel2.add(lblNombreComercial);

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel7.setText("Direccion:");
    jPanel2.add(jLabel7);

    txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtDireccionFocusLost(evt);
        }
    });
    jPanel2.add(txtDireccion);

    lblDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblDireccion.setText("*");
    jPanel2.add(lblDireccion);

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel9.setText("Obligado a Contabilidad:");
    jPanel2.add(jLabel9);

    chkContabilidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(chkContabilidad);

    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(jLabel10);

    jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel11.setText("Contribuyente Especial #:");
    jPanel2.add(jLabel11);

    txtContribuyente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtContribuyente.setText("0");
    txtContribuyente.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtContribuyenteKeyTyped(evt);
        }
    });
    jPanel2.add(txtContribuyente);

    lblContribuyente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(lblContribuyente);

    jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel13.setText("Email:");
    jPanel2.add(jLabel13);

    txtPropietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtPropietario.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtPropietarioFocusLost(evt);
        }
    });
    jPanel2.add(txtPropietario);

    lblPropietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblPropietario.setText("*");
    jPanel2.add(lblPropietario);

    jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel22.setText("Contraseña:");
    jPanel2.add(jLabel22);

    passClaveEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    passClaveEmail.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            passClaveEmailFocusLost(evt);
        }
    });
    jPanel2.add(passClaveEmail);

    lblClaveEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblClaveEmail.setText("*");
    jPanel2.add(lblClaveEmail);

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel4.setText("Establecimiento:");
    jPanel2.add(jLabel4);

    txtEstablecimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtEstablecimiento.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtEstablecimientoFocusLost(evt);
        }
    });
    txtEstablecimiento.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtEstablecimientoKeyTyped(evt);
        }
    });
    jPanel2.add(txtEstablecimiento);

    lblEstablecimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblEstablecimiento.setText("* Ej: 001");
    jPanel2.add(lblEstablecimiento);

    jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel20.setText("Punto de Emisión:");
    jPanel2.add(jLabel20);

    cbxEmision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(cbxEmision);

    btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnAgregar.setText("Agregar...");
    btnAgregar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAgregarActionPerformed(evt);
        }
    });
    jPanel2.add(btnAgregar);

    jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel15.setText("N° de Despachadores:");
    jPanel2.add(jLabel15);

    txtDespachadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDespachadores.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtDespachadoresFocusLost(evt);
        }
    });
    txtDespachadores.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtDespachadoresKeyTyped(evt);
        }
    });
    jPanel2.add(txtDespachadores);

    lblDespachadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblDespachadores.setText("*");
    jPanel2.add(lblDespachadores);

    jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel17.setText("Ambiente:");
    jPanel2.add(jLabel17);

    cbxAmbiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    cbxAmbiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pruebas", "Producción" }));
    jPanel2.add(cbxAmbiente);

    lblAmbiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(lblAmbiente);

    jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel19.setText("Certificado:");
    jPanel2.add(jLabel19);

    txtCertificado.setEditable(false);
    txtCertificado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(txtCertificado);

    btnSeleccionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnSeleccionar.setText("Seleccionar...");
    btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSeleccionarActionPerformed(evt);
        }
    });
    jPanel2.add(btnSeleccionar);

    jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel21.setText("Clave:");
    jPanel2.add(jLabel21);

    passClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    passClave.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            passClaveFocusLost(evt);
        }
    });
    jPanel2.add(passClave);

    lblClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblClave.setText("*");
    jPanel2.add(lblClave);

    jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel18.setText("Tipo Cierre de Turno:");
    jPanel2.add(jLabel18);

    cbxTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    cbxTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abierto", "Cerrado" }));
    jPanel2.add(cbxTurno);

    lblTuno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel2.add(lblTuno);

    getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

    btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGuardarActionPerformed(evt);
        }
    });
    jPanel3.add(btnGuardar);

    btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
        }
    });
    jPanel3.add(btnCancelar);

    getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRUCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRUCFocusLost
        // TODO add your handling code here:
        if (txtRUC.getText().length() == 0) {
            lblRUC.setText("* " + "Campo Obligatorio");
            lblRUC.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtRUCFocusLost

    private void txtRazonSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazonSocialFocusLost
        // TODO add your handling code here:
        if (txtRazonSocial.getText().length() == 0) {
            lblRazonSocial.setText("* " + "Campo Obligatorio");
            lblRazonSocial.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtRazonSocialFocusLost

    private void txtNombreComercialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreComercialFocusLost
        // TODO add your handling code here:
        if (txtNombreComercial.getText().length() == 0) {
            lblNombreComercial.setText("* " + "Campo Obligatorio");
            lblNombreComercial.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtNombreComercialFocusLost

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        // TODO add your handling code here:
        if (txtDespachadores.getText().length() == 0) {
            lblDireccion.setText("* " + "Campo Obligatorio");
            lblDireccion.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtDespachadoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDespachadoresFocusLost
        // TODO add your handling code here:
        if (txtDespachadores.getText().length() == 0) {
            lblDespachadores.setText("* " + "Campo Obligatorio");
            lblDespachadores.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtDespachadoresFocusLost

    private void passClaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passClaveFocusLost
        // TODO add your handling code here:
        if (new String(passClave.getPassword()).length() == 0) {
            lblClave.setText("* " + "Campo Obligatorio");
            lblClave.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_passClaveFocusLost

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo P12", "p12");
            fc.setFileFilter(filter);
            int open = fc.showOpenDialog(this);
            if (open == JFileChooser.APPROVE_OPTION) {
                file = fc.getSelectedFile();
                String name = file.getName();
                if (name.substring(name.lastIndexOf(".") + 1).equalsIgnoreCase("p12")) {
                    stream = new FileInputStream(file);
                    txtCertificado.setText(name.substring(0, name.length() - 4));
                    fileChanged = true;
                    txtCertificado.setForeground(java.awt.Color.BLACK);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe escoger un archivo P12.");
                }
            }
        } catch (FileNotFoundException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtRazonSocial.getText().length() != 0 && txtRUC.getText().length() != 0
                && txtNombreComercial.getText().length() != 0
                && txtDireccion.getText().length() != 0 && txtDireccion.getText().length() != 0
                && txtPropietario.getText().length() != 0 && new String(passClaveEmail.getPassword()).length() != 0
                && new String(passClave.getPassword()).length() != 0
                && !txtCertificado.getText().equalsIgnoreCase("Sin Certificado")) {
            if (btnGuardar.getText().equalsIgnoreCase("Guardar")) {
                fileChanged = false;
            }
            try {
                conn.consulta("SELECT ruc FROM datos_gasolinera");
                if (conn.getRowCount() == 0) {
                    conn.ejecutar("INSERT INTO datos_gasolinera (razon_social, ruc, nombre_comercial, direccion, obligado_llevar_contabilidad, "
                            + "contribuyente_especial, email_estacion, contraseña_mail, despachadores_turno, tipo_ambiente, contraseña_certificado, tipo_cierre_turnos) "
                            + "VALUES ('"
                            + txtRazonSocial.getText() + "', '"
                            + txtRUC.getText() + "', '"
                            + txtNombreComercial.getText() + "', '"
                            + txtDireccion.getText() + "', '"
                            + (chkContabilidad.isSelected() ? "SI" : "NO") + "', '"
                            + (txtContribuyente.getText().length() == 0 ? "0" : txtContribuyente.getText()) + "', '"
                            + txtPropietario.getText() + "', "
                            + "AES_ENCRYPT('" + new String(passClaveEmail.getPassword()) + "', 'thekey'), "
                            + Integer.parseInt(txtDespachadores.getText()) + ", "
                            + (cbxAmbiente.getSelectedIndex() + 1) + "', '"
                            + "AES_ENCRYPT('" + new String(passClave.getPassword()) + "', 'thekey'), "
                            + (cbxTurno.getSelectedIndex() + 1) + ")");
                    conn.psPrepararSentencias = conn.coneccion.prepareStatement("INSERT INTO datos_gasolinera (certificado_digital) VALUES (?)");
                    conn.psPrepararSentencias.setBinaryStream(1, stream, (int) file.length());
                    conn.psPrepararSentencias.executeUpdate();
                    conn.psPrepararSentencias.close();
                    for (int i = 0; i < pto.length; i++) {
                        String[] row = pto[i].split(",");
                        try {
                            conn.consulta("SELECT idpunto_emision FROM punto_emision ORDER BY idpunto_emision DESC LIMIT 1");
                            conn.ejecutar("INSERT INTO punto_emision "
                                    + "VALUES (" + (Integer)conn.getValueAt(0, 0) + ", '" + row[0] + "', '" + row[1] + "', '" + row[2] + "', 1)");
                        } catch (SQLException | IllegalStateException ex) {
                            System.err.println(ex.getMessage());
                        }
                    }
                    javax.swing.JOptionPane.showMessageDialog(this, "Datos agregados correctamente.");
                } else {
                    conn.ejecutar("UPDATE datos_gasolinera "
                            + "SET "
                            + "razon_social = '" + txtRazonSocial.getText() + "', "
                            + "ruc = '" + txtRUC.getText() + "', "
                            + "nombre_comercial = '" + txtNombreComercial.getText() + "', "
                            + "direccion = '" + txtDireccion.getText() + "', "
                            + "obligado_llevar_contabilidad = '" + (chkContabilidad.isSelected() ? "SI" : "NO") + "', "
                            + "contribuyente_especial = '" + (txtContribuyente.getText().length() == 0 ? "0" : txtContribuyente.getText()) + "', "
                            + "email_estacion = '" + txtPropietario.getText() + "', "
                            + "contraseña_mail = AES_ENCRYPT('" + new String(passClaveEmail.getPassword()) + "', 'thekey'), "
                            + "secuencia1_factura = '" + txtEstablecimiento.getText() + "', "
                            + "despachadores_turno = " + Integer.parseInt(txtDespachadores.getText()) + ", "
                            + "tipo_ambiente = '" + (cbxAmbiente.getSelectedIndex() + 1) + "', "
                            + "contraseña_certificado = AES_ENCRYPT('" + new String(passClave.getPassword()) + "', 'thekey'), "
                            + "tipo_cierre_turnos = " + (cbxTurno.getSelectedIndex() + 1));
                    if (fileChanged) {
                        conn.psPrepararSentencias = conn.coneccion.prepareStatement("UPDATE datos_gasolinera SET certificado_digital = ?");
                        conn.psPrepararSentencias.setBinaryStream(1, stream, (int) file.length());
                        conn.psPrepararSentencias.executeUpdate();
                        conn.psPrepararSentencias.close();
                    }
                    if (pto != null && puntosEmision != cbxEmision.getItemCount())
                    for (int i = 0; i < pto.length; i++) {
                        String[] row = pto[i].split(",");
                        try {
                            conn.consulta("SELECT idpunto_emision FROM punto_emision ORDER BY idpunto_emision DESC LIMIT 1");
                            conn.ejecutar("INSERT INTO punto_emision "
                                    + "VALUES (" + (Integer)conn.getValueAt(0, 0) + ", '" + row[0] + "', '" + row[1] + "', '" + row[2] + "', 1)");
                        } catch (SQLException | IllegalStateException ex) {
                            System.err.println(ex.getMessage());
                        }
                    }
                    javax.swing.JOptionPane.showMessageDialog(this, "Datos editados correctamente.");
                }
                dispose();
            } catch (SQLException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos obligatorios.");
            txtCertificado.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtRUC.getText().length() >= 13) {
            evt.consume();
        }
        if (txtRUC.getText().length() <= 13) {
            lblRUC.setText("* " + "Obligado 13 dígitos");
        } else {
            lblRUC.setText("* OK");
            lblRUC.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtRUCKeyTyped

    private void txtContribuyenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContribuyenteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContribuyenteKeyTyped

    private void txtDespachadoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDespachadoresKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDespachadoresKeyTyped

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
        // TODO add your handling code here:
        if (txtRazonSocial.getText().length() != 0) {
            lblRazonSocial.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtRazonSocialKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        conn.desconectar();
    }//GEN-LAST:event_formWindowClosed

    private void passClaveEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passClaveEmailFocusLost
        // TODO add your handling code here:
        if (new String(passClaveEmail.getPassword()).length() == 0) {
            lblClaveEmail.setText("* " + "Campo Obligatorio");
            lblClaveEmail.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_passClaveEmailFocusLost

    private void txtPropietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPropietarioFocusLost
        // TODO add your handling code here:
        if (txtPropietario.getText().length() == 0) {
            lblPropietario.setText("* " + "Campo Obligatorio");
            lblPropietario.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtPropietarioFocusLost

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            ptos = "";
            pto = null;
            txtAPtos.setText("");
            conn.consulta("SELECT * FROM punto_emision");
            if (conn.getRowCount() == 0) {
                pto1 = JOptionPane.showInputDialog(this,
                        "Ingrese Punto de Emisión para Facturación Electrónica en Playa:",
                        "Facturacion Electrónica",
                        JOptionPane.PLAIN_MESSAGE);
                if (conn.getRowCount() < 2) {
                    pto2 = JOptionPane.showInputDialog(this,
                            "Ingrese Punto de Emisión para Facturación Electrónica en Oficinas:",
                            "Facturacion Electrónica",
                            JOptionPane.PLAIN_MESSAGE);
                    this.setEnabled(false);
                    frameEmision.setVisible(true);
                    txtAPtos.append(String.format("%10s   %-40s%12s\n", pto1, "", ""));
                    txtAPtos.append(String.format("%10s   %-40s%12s\n", pto2, "", ""));
                }
            } else {
                this.setEnabled(false);
                frameEmision.setVisible(true);
                conn.consulta("SELECT s2 FROM punto_emision LIMIT 2");
                pto1 = (String) conn.getValueAt(0, 0);
                pto2 = (String) conn.getValueAt(1, 0);
                txtAPtos.append(String.format("%10s   %-40s%12s\n", pto1, "", ""));
                txtAPtos.append(String.format("%10s   %-40s%12s\n", pto2, "", ""));
                conn.consulta("SELECT * FROM punto_emision");
                int puntos = conn.getRowCount();
                conn.consulta("SELECT s2, autorizacion, fecha_vencimiento FROM punto_emision LIMIT 3, " + puntos);
                for (int i = 0; i < conn.getRowCount(); i++) {
                    txtAPtos.append(String.format("%10s   %-40s%12s\n", (String) conn.getValueAt(i, 0), 
                            (String) conn.getValueAt(i, 1), 
                            (String) conn.getValueAt(i, 2)));
                }
            }

        } catch (SQLException | IllegalStateException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtEstablecimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstablecimientoFocusLost
        // TODO add your handling code here:
        if (txtEstablecimiento.getText().length() == 0) {
            lblEstablecimiento.setText("* " + "Campo Obligatorio");
            lblEstablecimiento.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_txtEstablecimientoFocusLost

    private void txtEstablecimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstablecimientoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '\t') {
            evt.consume();
        }
    }//GEN-LAST:event_txtEstablecimientoKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        /*txtAPtos.append(String.format("%10s   %-40s%12s\n", txtPtoEmision.getText(), txtAutorizacion.getText(), String.format("%1$tY/%1$tm/%1$td", fechaVencimiento.getCurrent())));
        ptos += txtPtoEmision.getText() + "," + txtAutorizacion.getText() + "," + fechaVencimiento.getText() + "\n";
       */ System.out.println(ptos);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        pto = ptos.split("\n");
        for (int i = 0; i < pto.length; i++) {
            String[] row = pto[i].split(",");
            cbxEmision.addItem(row[0]);
        }
        ptos = "";
        frameEmision.setVisible(false);
        this.setEnabled(true);
        txtEDS.requestFocus();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarPtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPtoActionPerformed
        // TODO add your handling code here:
        ptos = "";
        pto = null;
        frameEmision.setVisible(false);
        this.setEnabled(true);
        txtEDS.requestFocus();
    }//GEN-LAST:event_btnCancelarPtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DatosGasolinera("root", "manager").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarPto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox cbxAmbiente;
    private javax.swing.JComboBox cbxEmision;
    private javax.swing.JComboBox cbxTurno;
    private javax.swing.JCheckBox chkContabilidad;
    private javax.swing.JFrame frameEmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmbiente;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblClaveEmail;
    private javax.swing.JLabel lblContribuyente;
    private javax.swing.JLabel lblDespachadores;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEDS;
    private javax.swing.JLabel lblEstablecimiento;
    private javax.swing.JLabel lblNombreComercial;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblTuno;
    private javax.swing.JPasswordField passClave;
    private javax.swing.JPasswordField passClaveEmail;
    private javax.swing.JTextArea txtAPtos;
    private javax.swing.JTextField txtAutorizacion;
    private javax.swing.JTextField txtCertificado;
    private javax.swing.JTextField txtContribuyente;
    private javax.swing.JTextField txtDespachadores;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEDS;
    private javax.swing.JTextField txtEstablecimiento;
    private javax.swing.JTextField txtNombreComercial;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtPtoEmision;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
