package Principal;


import conexion.ConnectionTableDB;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author r
 */
public class plaqueados extends javax.swing.JFrame {

    /**
     * Creates new form plaqueados
     */
    ConnectionTableDB model;

    public plaqueados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Ingresar Archivo de Plaqueados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
         try {
            model = new ConnectionTableDB("root", "manager", "adv_facturacion", "", false);
            model.ejecutar("delete from plaqueados");
            JOptionPane.showMessageDialog(this, "Plaqueados Anteriores borrados correctamente");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(plaqueados.class.getName()).log(Level.SEVERE, null, ex);
        }

        model.desconectar(); 
        
        
        
        Workbook workbook;
        JFileChooser a = new JFileChooser();
        FileNameExtensionFilter filtroExcel = new FileNameExtensionFilter("Excel", "xls");
        a.setFileFilter(filtroExcel);
        a.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int seleccion = a.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File f = a.getSelectedFile();
            try {
                workbook = Workbook.getWorkbook(f); //Pasamos el excel que vamos a leer
                Sheet sheet = workbook.getSheet(0); //Seleccionamos la hoja que vamos a leer
                String nombre,nombre1 = "";

                for (int fila = 1; fila < sheet.getRows(); fila++) { //recorremos las filas
                    for (int columna = 0; columna < sheet.getColumns(); columna++) { //recorremos las columnas
                        nombre = sheet.getCell(columna, fila).getContents(); //setear la celda leida a nombre
                        
                        System.out.print(nombre.replace(" ", "0") + "    ");
                        
                        if(nombre.length()==8){
                        
                        
                            nombre1=nombre.replace(" ", "");
                            
                        }else{
                        
                            
                            nombre1=nombre.replace(" ", "0");
                        
                        }
                        System.out.print(nombre.length());
                        if (!nombre.equals("")) {
                            try {
                                model = new ConnectionTableDB("root", "manager", "adv_facturacion", "", false);
                                model.ejecutar("insert into plaqueados(placa,fecha) VALUES ('" + nombre1 + "',curdate())");
                                
                                System.out.println("insert into plaqueados(placa,fecha) VALUES ('" + nombre1 + "',0000-00-00)");
// TODO add your handling code here:
                            } catch (SQLException ex) {
                                Logger.getLogger(plaqueados.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            model.desconectar();
                        }

// imprimir nombre
                    }
                    System.out.println("\n");
                }
                JOptionPane.showMessageDialog(this, "agregado correctamente");

            } catch (IOException ex) {
                Logger.getLogger(plaqueados.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(plaqueados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plaqueados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plaqueados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plaqueados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plaqueados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plaqueados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
