/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import conexion.ConnectionTableDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author USUARIO
 */
public class productosPorFactura extends javax.swing.JFrame {

    /**
     * Creates new form productosPorFactura
     */
            ConnectionTableDB model;
 ConnectionTableDB model2;
    public productosPorFactura(String usu,String contra,String inicial,String ffinal,String hini,String hfin,String usua,String codbar) {
        initComponents();
                 DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
tcr.setHorizontalAlignment(SwingConstants.CENTER);
        
        String consulta1="";
        try {
            
            System.out.println("select factura.numero,factura.fecha,factura.hora,cliente.cedula_ruc,cliente.nombre,usuarios.nombre,factura_detalle.cantidad\n" +
"from factura,cliente,usuarios,factura_detalle,producto\n" +
" where punto_emision_idpunto_emision=3 and fecha between '"+inicial+"' and '"+ffinal+"' and cliente_idcliente=idcliente\n" +
" and usuarios_idusuarios=idusuarios \n" +
" and factura.idfactura=factura_detalle.factura_idfactura and factura_detalle.producto_idproducto=producto.idproducto\n" +
"and producto.codigo_barra='"+codbar+"'");
            
            
            
            consulta1="select factura.numero,factura.fecha,factura.hora,cliente.cedula_ruc,cliente.nombre as NOMBRE_CLIENTE,usuarios.nombre as NOMBRE_VENDEDOR,factura_detalle.cantidad\n" +
"from factura,cliente,usuarios,factura_detalle,producto\n" +
" where punto_emision_idpunto_emision=3 and fecha between '"+inicial+"' and '"+ffinal+"' and cliente_idcliente=idcliente\n" +
" and usuarios_idusuarios=idusuarios \n" +
" and factura.idfactura=factura_detalle.factura_idfactura and factura_detalle.producto_idproducto=producto.idproducto\n" +
"and producto.codigo_barra='"+codbar+"'";
            
                   if((!hini.equalsIgnoreCase("")) & (!hfin.equalsIgnoreCase(""))){
                   consulta1=consulta1+" and hora between '"+hini+"' and '"+hfin+"'";
                   }

                   if(!usua.equalsIgnoreCase("")){
                   consulta1=consulta1+" and usuarios.nombre ='"+usua+"'";
                   }
                  //JOptionPane.showMessageDialog(this, usua);
            model2=new ConnectionTableDB(usu, contra, "adv_facturacion","select nombre from producto where codigo_barra='"+codbar+"'" , false);
            lblProducto.setText(String.valueOf(model2.getValueAt(0, 0)));
            model2.desconectar();
            model = new ConnectionTableDB(usu, contra, "adv_facturacion",consulta1 , false);
 
            
            tablaReporteProd.setModel(model);
            for(int i=0;i<tablaReporteProd.getColumnCount();i++){
            tablaReporteProd.getColumnModel().getColumn(i).setCellRenderer(tcr);
            }
            //

            
            
        } catch (SQLException ex) {
            Logger.getLogger(prepagoGasolina.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporteProd = new javax.swing.JTable();
        lblProducto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos por Factura");

        tablaReporteProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaReporteProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProducto;
    public javax.swing.JTable tablaReporteProd;
    // End of variables declaration//GEN-END:variables
}
