/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import conexion.conexion_facturacion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author r
 */
public class reporte_clientes_credito extends javax.swing.JInternalFrame {

    /**
     * Creates new form reporte_clientes_credito
     */
    String usuario, contraseña;
    private DefaultListModel modelo = new DefaultListModel();
    MiModelo litabla = new MiModelo();

    public reporte_clientes_credito(String usuario, String contraseña) {
        this.usuario = usuario;
        this.contraseña = contraseña;

        initComponents();


        tabla.setModel(litabla);


        
        litabla.addColumn("Razon Social");
        litabla.addColumn("DI");
        litabla.addColumn("Cupo Credito");
        litabla.addColumn("Deuda Actual");


        llenar();

    }

    public void llenar() {

        try {
            String nombre;
            conexion_facturacion n = new conexion_facturacion(usuario, contraseña);
            n.conectar();

            nombre = "SELECT\n" +
"     cliente.`nombre` AS cliente_nombre,\n" +
"     cliente.`cedula_ruc` AS cliente_cedula_ruc,\n" +
"     credito_cliente.`cupo_cliente` AS credito_cliente_cupo_cliente\n" +
"FROM\n" +
"     `cliente` cliente INNER JOIN `credito_cliente` credito_cliente ON cliente.`idcliente` = credito_cliente.`cliente_idcliente`"
                    + "group by cedula_ruc";


            ResultSet consultan = n.consulta(nombre);

            Object datos[] = new Object[3];

            while (consultan.next()) {
                for (int i = 0; i < 3; i++) {

                    
                    
                    datos[i] = consultan.getObject(i + 1);
                      nombre = "SELECT\n" +
        "     cliente.`nombre` AS cliente_nombre,\n" +
        "     cliente.`cedula_ruc` AS cliente_cedula_ruc,\n" +
        "     credito_cliente.`cupo_cliente` AS credito_cliente_cupo_cliente\n" +
         "FROM\n" +
        "     `cliente` cliente INNER JOIN `credito_cliente` credito_cliente ON cliente.`idcliente` = credito_cliente.`cliente_idcliente`"
                    + "group by cedula_ruc";

                      

            ResultSet consultan1 = n.consulta(nombre);

                    //datos[i] = consultac.getObject(i + 1);
                }
                litabla.addRow(datos);
            }

            tabla.setModel(litabla);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reporte_clientes_credito.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reporte_clientes_credito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public class MiModelo extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {

            return false;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte_clientes_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte_clientes_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte_clientes_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte_clientes_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new reporte_clientes_credito().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
