/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package configuracion;

import conexion.conexion_facturacion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author r
 */
public class ingresar_datos_gasolinera extends javax.swing.JFrame {

    public String usu, contra;

    /**
     * Creates new form ingresar_datos_gasolinera
     */
    public ingresar_datos_gasolinera(String usuario, String contraseña) {
        try {


            initComponents();
            conexion_facturacion n = new conexion_facturacion(usuario, contraseña);

            n.conectar();

            Statement st_d = n.coneccion.createStatement();
            ResultSet rid = st_d.executeQuery("SELECT * FROM datos_gasolinera;");

            while (rid.next()) {

                rs.setText(rid.getString(2));
                np.setText(rid.getString(5));
                direccion.setText(rid.getString(4));
                ruc.setText(rid.getString(3));
                s1f.setText(rid.getString(6));
                s2f.setText(rid.getString(7));
                asri.setText(rid.getString(8));
                tel.setText(rid.getString(9));

            }




        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rs = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        np = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ruc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s1f = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        s2f = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        asri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(9, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Razon Social");
        jPanel1.add(jLabel1);
        jPanel1.add(rs);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre Propietario");
        jPanel1.add(jLabel2);
        jPanel1.add(np);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("RUC");
        jPanel1.add(jLabel3);
        jPanel1.add(ruc);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Direccion");
        jPanel1.add(jLabel4);
        jPanel1.add(direccion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Secuencia 1 Facturas");
        jPanel1.add(jLabel5);
        jPanel1.add(s1f);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Secuencia 2 Facturas");
        jPanel1.add(jLabel6);
        jPanel1.add(s2f);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Autorizacion SRi");
        jPanel1.add(jLabel7);
        jPanel1.add(asri);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Telefono");
        jPanel1.add(jLabel8);
        jPanel1.add(tel);

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conexion_facturacion conectar = new conexion_facturacion(usu, contra);

            conectar.conectar();

            if (rs.getText().equalsIgnoreCase(" ")) {

                PreparedStatement gf = conectar.coneccion.prepareStatement("insert into datos_gasolinera values (?,?,?,?,?,?,?,?,?,?)");

                gf.setInt(1, 1);
                gf.setString(2, rs.getText());
                gf.setString(3, ruc.getText());
                gf.setString(4, direccion.getText());
                gf.setString(5, np.getText());
                gf.setString(6, s1f.getText());
                gf.setString(7, s2f.getText());
                gf.setString(8, asri.getText());
                gf.setString(9, tel.getText());
                gf.execute();
                this.setVisible(false);

            } else {
                Statement st3 = conectar.coneccion.createStatement();
                String consulta3 = "UPDATE `adv_facturacion`.`datos_gasolinera` SET  `ruc`='" + ruc.getText() + "',nombre_propietario='" + np.getText() + "' ,`direccion`='" + direccion.getText() + "', `secuencia1_factura`='" + s1f.getText() + "', `secuencia2_factura`='" + s2f.getText() + "', `autorizacion_sri`='" + asri.getText() + "', `telefono`='" + tel.getText() + " ' WHERE `iddatos_gasolinera`='1';";
                st3.executeUpdate(consulta3);


                  JOptionPane.showMessageDialog(this, "Configuracion Ingresada Correctamente");
                this.setVisible(false);



            }


        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresar_datos_gasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresar_datos_gasolinera("", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asri;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField np;
    private javax.swing.JTextField rs;
    private javax.swing.JTextField ruc;
    private javax.swing.JTextField s1f;
    private javax.swing.JTextField s2f;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables

    public void usuarios(String usuario, String contraseña) {

        contra = contraseña;
        usu = usuario;

    }
}
