/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;


import conexion.conexion_facturacion;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author r
 */
public class buscarcliente extends javax.swing.JFrame {
    public String usu,contra;
    /**
     * Creates new form buscar
     */
    public DefaultListModel modelo = new DefaultListModel();
    String usuarioa;
    MiModelo litabla = new MiModelo();
    private JTextField clientes = null;
     private JTextField rucc = null;
    public String nombre, ruc, codigo;
    public String nsurtidor;
    File surtidor;

    public buscarcliente() {
    }

    public buscarcliente(JTextField ncliente , JTextField ruc1) {

        this.clientes = ncliente;
        this.rucc=ruc1;
        initComponents();
        JTable tabla1 = new JTable(litabla);

        this.setLocation(250, 50);
        litabla.addColumn("Nombre");
        litabla.addColumn("Cedula/ruc");
        litabla.addColumn("Direccion");
        litabla.addColumn("Codigo");
        litabla.addColumn("Telefono");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ncliente = new javax.swing.JTextField();
        rcliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ccliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        ncliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nclienteKeyTyped(evt);
            }
        });

        rcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rclienteKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("RUC/CEDULA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CODIGO");

        ccliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cclienteKeyTyped(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ccliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(209, 478, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nclienteKeyTyped
        nombre = ncliente.getText();
        try {

            LimpiarJTable();
            int id = 0, telefono = 0;
            String nombrec = null, mail = null, cedula;
            System.out.println(nombre);


            conexion_facturacion n = new conexion_facturacion(usu, contra);
            n.conectar();

            nombre = "SELECT nombre,cedula_ruc,direccion,codigo,telefono FROM cliente  WHERE  (nombre) regexp ( '" + nombre + "' ) order by idcliente";
            System.out.println(nombre);
            ResultSet consultan = n.consulta(nombre);

            Object datos[] = new Object[5];

            while (consultan.next()) {
                for (int i = 0; i < 5; i++) {
                    datos[i] = consultan.getObject(i + 1);

                    //datos[i] = consultac.getObject(i + 1);
                }
                litabla.addRow(datos);
            }

            tabla.setModel(litabla);

        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
            System.out.println("error sql");
        } catch (java.lang.NullPointerException ex) {

            System.out.println("cliente no encontrado");

        }
    }//GEN-LAST:event_nclienteKeyTyped

    private void rclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rclienteKeyTyped
        ruc = rcliente.getText();
        try {

            LimpiarJTable();
            int id = 0, telefono = 0;
            String nombrec = null, mail = null, cedula;
            System.out.println(nombre);


            conexion_facturacion n = new conexion_facturacion(usu, contra);
            n.conectar();

            nombrec = "SELECT nombre,cedula_ruc,direccion,codigo FROM cliente  WHERE  (cedula_ruc) regexp ( '" + ruc + "' ) order by idcliente";
            System.out.println(nombrec);
            ResultSet consultan = n.consulta(nombrec);

            Object datos[] = new Object[3];

            while (consultan.next()) {
                for (int i = 0; i < 3; i++) {
                    datos[i] = consultan.getObject(i + 1);

                    //datos[i] = consultac.getObject(i + 1);
                }
                litabla.addRow(datos);
            }

            tabla.setModel(litabla);

        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
            System.out.println("error sql");
        } catch (java.lang.NullPointerException ex) {

            System.out.println("cliente no encontrado");

        }
    }//GEN-LAST:event_rclienteKeyTyped

    private void cclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cclienteKeyTyped
        codigo = ccliente.getText();
        try {

            LimpiarJTable();
            int id = 0, telefono = 0;
            String nombrec = null, mail = null, cedula;
            System.out.println(nombre);


            conexion_facturacion n = new conexion_facturacion(usu, contra);
            n.conectar();

            nombrec = "SELECT nombre,cedula_ruc,direccion,codigo FROM cliente  WHERE  (codigo) regexp ( '" + codigo + "' ) order by idcliente";
            System.out.println(nombrec);
            ResultSet consultan = n.consulta(nombrec);

            Object datos[] = new Object[3];

            while (consultan.next()) {
                for (int i = 0; i < 3; i++) {
                    datos[i] = consultan.getObject(i + 1);

                    //datos[i] = consultac.getObject(i + 1);
                }
                litabla.addRow(datos);
            }

            tabla.setModel(litabla);

        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
            System.out.println("error sql");
        } catch (java.lang.NullPointerException ex) {

            System.out.println("cliente no encontrado");

        }
    }//GEN-LAST:event_cclienteKeyTyped

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        File f = null;



        DefaultTableModel tm = (DefaultTableModel) tabla.getModel();
        String cedula = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 1));
        String nombrec = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 0));
        String direccion = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 2));
        String telf = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 4));


        
        


        


        clientes.setText(nombrec);
        rucc.setText(cedula);




//Escritura
        
        this.setVisible(false);
    }//GEN-LAST:event_tablaMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarcliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarcliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarcliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarcliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarcliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ncliente;
    private javax.swing.JTextField rcliente;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    public class MiModelo extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {

            return true;

        }
    }

    public void LimpiarJTable() {

        litabla.setNumRows(0);


    }


public void usuarios(String usuario,String contraseña){

contra=contraseña;
usu=usuario;
    
}





}
